apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    env:
    - key: var1
      value: var1
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
