apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-b
  name: pod-b
  namespace: ggckad-s0
spec:
  containers:
  - image: kubegoldenguide/alpine-spin:1.0.0
    name: pod-a
    resources: {}
  - image: nginx:1.7.9
    name: pod-b
    ports:
    - name: web
      containerPort: 80
      protocol: TCP 
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
