apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: question-two-pod
  name: question-two-pod
spec:
  containers:
  - image: kubegoldenguide/alpine-spin:1.0.0
    name: question-two-pod
    envFrom:
      - configMapRef:
          name: app-config
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
