apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: q3
  name: q3
spec:
  securityContext:
    fsGroup: 3000
  containers:
  - image: kubegoldenguide/alpine-spin:1.0.0
    name: c1
    resources: {}
    securityContext:
        runAsUser: 1000
  - image: kubegoldenguide/alpine-spin:1.0.0
    name: c2
    securityContext:
      runAsUser: 2000
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
