apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: question-13-pod
  name: question-13-pod
spec:
  containers:
  - image: kubegoldenguide/question-thirteen
    name: question-13-pod
    livenessProbe:
       httpGet:
        path: /health
        port: 8000
       initialDelaySeconds: 60
    readinessProbe:
        httpGet:
          path: /health 
          port: 8000
        initialDelaySeconds: 60
        periodSeconds: 5
    ports:
    - containerPort: 8000
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
