apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    hello: sahib
    helo: punj
  name: temp
spec:
  containers:
  - image: nginx
    name: temp
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
