apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: multicontainer
  name: multicontainer
spec:
  containers:
  - image: nginx
    name: multicontainer
    ports:
    - containerPort: 80
    resources: {}
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: vol
  initContainers:
  - image: busybox
    name: multicontainer1
    args:
    - /bin/sh
    - wget -O /work-dir/index.html http://neverssl.com/online 
    resources: {}
    volumeMounts:
    - mountPath: /work-dir
      name: vol
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  volumes:
  - name: vol
    emptyDir: {}
status: {}
