apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx3
  name: nginx3
spec:
  containers:
  - image: nginx
    name: nginx3
    resources:
      limits:
        memory: 512Mi
        cpu: 200m
      requests:  
        memory: 256Mi
        cpu: 100m
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
